# A list of resources that contain TOSCA type definitions and that should be
# loaded by the plugin on initialisation.
defaultTypes:
- https://github.com/alien4cloud/tosca-normative-types/archive/master.zip
